#baseURL = "https://neutronimaging-dev.pages.ornl.gov/"
languageCode = "en-US"
defaultContentLanguage = "en"

title = "Hugo Learn Documentation"
theme = "hugo-theme-learn"
themesdir = "themes"
metaDataFormat = "yaml"
defaultContentLanguageInSubdir= false

[params]
  editURL = ""
  description = "ORNL Neutron Imaging for Users Home Page"
  author = "Jean Bilheux"
  showVisitedLinks = true
  themeVariant = "blue"

[outputs]
home = [ "HTML", "RSS", "JSON"]

[Languages]
[Languages.en]
title = "Documentation for Hugo Learn Theme"
weight = 1
languageName = "English"

#[[Languages.en.menu.shortcuts]]
#name = "<i class='fa fa-github'></i> Github Repos"
#url = "github"
#weight = 11

[[Languages.en.menu.shortcuts]]
name = "<i class='fa fa-camera'></i> Photo Gallery"
url = "/showcase"
weight = 12

[[Languages.en.menu.shortcuts]]
name = "<i class='fa fa-book'></i> Publications"
url = "https://neutronimaging-publications.pages.ornl.gov"
weight = 13

[[Languages.en.menu.shortcuts]]
name = "<i class='fa fa-user-circle'></i> Contacts"
url = "/credits"
weight = 30

